### ISSUE TITLE
autoReplaceSSL assumes property present in response

### ISSUE THREAD

**Issue by JAAulde** [checkdomain/Comodo#12]
When the `autoReplaceSSL` method processes the response from the API, it assumes `certificateID` is present in that response. According to the [docs for the !AutoReplaceSSL end point](https://sectigo.com/uploads/files/AutoReplaceSSL-v1.23.pdf), however, this property is only present when the request sends a param called `showCertificateID` with a value of `Y`.

Without that parameter present, the library causes an Undefined Index warning. In Laravel, these warnings are set up to throw exceptions. So although it's only a warning, it is problematic in a large set of environments.

This API wrapper should either check that `showCertificateID` was set and equal to `Y` in the request before attempting to access `certificateID` in the response, OR it should force `showCertificateID` into the request with a value of `Y` so that the response property is always present.

My workaround for this right now is to manually add `showCertificateID` to the params I give to `autoReplaceSSL`.

**Comment by TPete** [comment]
Thanks @JAAulde
