### ISSUE TITLE
Release 2.4.0 not available in packagist

### ISSUE THREAD

**Issue by JAAulde** [checkdomain/Comodo#16]
This project's [packagist listing](https://packagist.org/packages/checkdomain/comodo) is [not auto updated](https://packagist.org/about#how-to-update-packages) so the latest release, 2.4.0, cannot be installed via composer.

**Comment by FlorianKoerner** [comment]
Thanks for the information. The new version is now available.

**Comment by JAAulde** [comment]
Thanks!
